version: '2'
services:
    gktestjhipster-app:
        image: gktestjhipster
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gktestjhipster-mysql:3306/gktestjhipster?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8087:8087
    gktestjhipster-mysql:
        extends:
            file: mysql.yml
            service: gktestjhipster-mysql
